//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EshopWorld.Strada.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EshopWorld.Strada.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;_id&quot;: &quot;5aec7bbfeb4c738f92da5137&quot;,
        ///    &quot;index&quot;: 0,
        ///    &quot;guid&quot;: &quot;40c7a6fd-58a4-4dc9-afad-78c6f2eefab3&quot;,
        ///    &quot;isActive&quot;: false,
        ///    &quot;balance&quot;: &quot;$2,444.98&quot;,
        ///    &quot;picture&quot;: &quot;http://placehold.it/32x32&quot;,
        ///    &quot;age&quot;: 20,
        ///    &quot;eyeColor&quot;: &quot;brown&quot;,
        ///    &quot;name&quot;: &quot;Tammi Buchanan&quot;,
        ///    &quot;gender&quot;: &quot;female&quot;,
        ///    &quot;company&quot;: &quot;PLASMOX&quot;,
        ///    &quot;email&quot;: &quot;tammibuchanan@plasmox.com&quot;,
        ///    &quot;phone&quot;: &quot;+1 (827) 516-2994&quot;,
        ///    &quot;address&quot;: &quot;757 Chapel Street, Lemoyne, Ohio, 1330&quot;,
        ///    &quot;about&quot;: &quot;Ea quis est deserunt  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleFile {
            get {
                return ResourceManager.GetString("SampleFile", resourceCulture);
            }
        }
    }
}
