//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshopworld.Strada.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eshopworld.Strada.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;ShopperCurrencyPaymentAmount&quot;: {
        ///		&quot;CurrencyCodeIso&quot;: &quot;EUR&quot;,
        ///		&quot;Currency&quot;: {
        ///			&quot;Iso&quot;: &quot;EUR&quot;,
        ///			&quot;Name&quot;: &quot;Euro&quot;,
        ///			&quot;Exponent&quot;: 2,
        ///			&quot;Id&quot;: 1
        ///		},
        ///		&quot;Value&quot;: 104.0
        ///	},
        ///	&quot;RetailerCurrencyPaymentAmount&quot;: {
        ///		&quot;CurrencyCodeIso&quot;: &quot;EUR&quot;,
        ///		&quot;Currency&quot;: {
        ///			&quot;Iso&quot;: &quot;EUR&quot;,
        ///			&quot;Name&quot;: &quot;Euro&quot;,
        ///			&quot;Exponent&quot;: 2,
        ///			&quot;Id&quot;: 1
        ///		},
        ///		&quot;Value&quot;: 104.0
        ///	},
        ///	&quot;EShopWorldCurrencyPaymentAmount&quot;: {
        ///		&quot;CurrencyCodeIso&quot;: &quot;EUR&quot;,
        ///		&quot;Currency&quot;: {
        ///			&quot;Iso&quot;: &quot;EUR&quot;,
        ///			&quot;Name&quot;: &quot;Euro&quot;,
        ///			&quot;Exponent&quot;: 2,
        ///			&quot;Id [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterOrder {
            get {
                return ResourceManager.GetString("MasterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;OrderCode&quot;: &quot;08d22af2-6337-4115-8e40-859c0c843e24&quot;,
        ///  &quot;RetailerCartId&quot;: &quot;EVO_20181106162638795&quot;,
        ///  &quot;OrderItems&quot;: [{
        ///      &quot;OrderArticles&quot;: [{
        ///        &quot;Charges&quot;: [{
        ///            &quot;Name&quot;: &quot;InputItem&quot;,
        ///            &quot;ExactValue&quot;: {
        ///              &quot;CurrencyCodeIso&quot;: &quot;RON&quot;,
        ///              &quot;Currency&quot;: {
        ///                &quot;Iso&quot;: &quot;RON&quot;,
        ///                &quot;Name&quot;: &quot;Romanian new leu&quot;,
        ///                &quot;Exponent&quot;: 2,
        ///                &quot;Id&quot;: 18
        ///              },
        ///              &quot;Value&quot;: 5977.8633333333
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
